name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
